package(default_visibility=['//visibility:public'])

py_binary(
    name = 'demo_py3only',
    srcs = [
        'demo_py3only.py',
    ],
)

py_test(
    name = 'py3only_test',
    srcs = [
        'py3only_test.py',
    ],
)
