licenses(['notice'])

cc_binary(
    name = 'gflags_example',
    srcs = [
        'gflags_example.cc',
    ],
    deps = [
        '//external:gflags',
    ],
)

cc_binary(
    name = 'glog_example',
    srcs = [
        'glog_example.cc',
    ],
    deps = [
        '//external:gflags',
        '//external:glog',
    ],
)
