licenses(['notice'])

cc_binary(
    name = 'gflags_example',
    srcs = [
        'gflags_example.cc',
    ],
    deps = [
        '//third_party/gflags',
    ],
)

cc_binary(
    name = 'glog_example',
    srcs = [
        'glog_example.cc',
    ],
    deps = [
        '//third_party/glog',
    ],
)

cc_binary(
    name = 'helloworld',
    srcs = [
        'helloworld.cc',
    ],
)
