'''Implement a Bazel extra_action that generates _compile_command files.

The generated _compile_command files are consumed by
generate_compile_commands.py.
'''

import argparse
import json
import subprocess

# The module below is generated by running protoc on the file below:
# pylint: disable=line-too-long
#       https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/extra_actions_base.proto
# For easy reference, a copy of the file is stored in this same directory.
import extra_actions_base_pb2


def update_parser(parser):
    '''Add arguments to the parser object.
    '''
    parser.add_argument(
        'extra_action_bin',
        help='the file name of the serialized extra_action message'
    )
    parser.add_argument('output_file', help='output file name')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    update_parser(parser)

    args = parser.parse_args()

    # pylint: disable=no-member
    #
    # OK to ignore the pylint no-member error because they are dynamically
    # loaded at runtime.
    action = extra_actions_base_pb2.ExtraActionInfo()
    with open(args.extra_action_bin, 'rb') as f:
        action.MergeFromString(f.read())
    cpp_compile_info = action.Extensions[
        extra_actions_base_pb2.CppCompileInfo.cpp_compile_info
    ]
    # pylint: enable=no-member

    cmd = [
        cpp_compile_info.tool,
        '-c',
        cpp_compile_info.source_file,
        '-o',
        cpp_compile_info.output_file,
    ] + [str(x) for x in cpp_compile_info.compiler_option]
    cmdstr = subprocess.list2cmdline(cmd)
    source_fname = cpp_compile_info.source_file

    data = {'command': cmdstr, 'file': source_fname}
    # Blacklisted files result in empty json objects.
    # TODO: Formalize the blacklisting of files.
    if source_fname.startswith('third_party/'):
        data = {}
    with open(args.output_file, 'w') as f:
        json.dump(data, f, sort_keys=True, indent=4)


if __name__ == '__main__':
    main()
