load('@io_bazel_skydoc//skylark:skylark.bzl', 'skylark_library')

skylark_library(
    name = 'build_defs',
    visibility = [
        '//visibility:public',
    ],
    srcs = glob([
        '*.bzl',
    ]),
)
